Bump MSRV to 1.85
```
info: running `rustup run 1.76 cargo check` on macrotest (1/1)
error: failed to download `serde_spanned v1.1.1`

Caused by:
  unable to get packages from source

Caused by:
  failed to download replaced source registry `crates-io`

Caused by:
  failed to parse manifest at `/home/kriskras99/.cargo/registry/src/index.crates.io-6f17d22bba15001f/serde_spanned-1.1.1/Cargo.toml`

Caused by:
  feature `edition2024` is required

  The package requires the Cargo feature called `edition2024`, but that feature is not stabilized in this version of Cargo (1.76.0 (c84b36747 2024-01-18)).
  Consider trying a newer version of Cargo (this may require the nightly release).
  See https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#edition-2024 for more information about the status of this feature.
error: process didn't exit successfully: `rustup run 1.76 cargo check --manifest-path Cargo.toml` (exit status: 101)
```