Bump MSRV to 1.60
syn 2.0.57 requires it.

```
error: failed to select a version for the requirement `syn = "=2.0.57"`
candidate versions found which didn't match: 2.0.56, 2.0.55, 2.0.54, ...
location searched: crates.io index
```